/**
 * ScaffoldModal.tsx
 * CodeCrafters-style starter scaffold generated from the loaded repo.
 * Left: scaffold file tree (reuses FileTree in embedded mode).
 * Right: code preview of the selected file + its purpose.
 * Actions: Download ZIP (jszip) · Open in StackBlitz.
 */
import { useEffect, useMemo, useState } from "react";
import JSZip from "jszip";
import type { Scaffold, ScaffoldFile } from "../api/features";
import FileTree from "./FileTree";
import { toast } from "./Toasts";
import { X, Download, ExternalLink, Zap, Copy, Check } from "lucide-react";

interface Props {
  open: boolean;
  scaffold: Scaffold | null;
  onClose: () => void;
}

const TEMPLATE_BY_TYPE: Array<[RegExp, string]> = [
  [/react/i, "react"],
  [/next/i, "next"],
  [/vue/i, "vue"],
  [/svelte/i, "svelte"],
  [/static|html/i, "static"],
];

function stackblitzTemplate(projectType: string): string {
  for (const [re, tpl] of TEMPLATE_BY_TYPE) {
    if (re.test(projectType)) return tpl;
  }
  return "node"; // generic JS/TS runner — Python scaffolds open as editable files
}

function downloadBlob(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

export default function ScaffoldModal({ open, scaffold, onClose }: Props) {
  const [selectedPath, setSelectedPath] = useState<string | null>(null);
  const [zipping, setZipping] = useState(false);
  const [copied, setCopied] = useState(false);

  const files: ScaffoldFile[] = scaffold?.files ?? [];
  const selected = useMemo(
    () => files.find((f) => f.path === selectedPath) ?? files[0] ?? null,
    [files, selectedPath],
  );

  // Preselect the README stub (the Stage 1/2/3 guide) when it exists
  useEffect(() => {
    if (!open || files.length === 0) return;
    const readme = files.find((f) => /(^|\/)readme\.md$/i.test(f.path));
    setSelectedPath(readme?.path ?? files[0].path);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [open, scaffold]);

  // Close on Escape
  useEffect(() => {
    if (!open) return;
    const onKey = (e: KeyboardEvent) => {
      if (e.key === "Escape") onClose();
    };
    document.addEventListener("keydown", onKey);
    return () => document.removeEventListener("keydown", onKey);
  }, [open, onClose]);

  if (!open || !scaffold) return null;

  const rawNodes = files.map((f) => ({ type: "file", label: f.path }));

  const copyContent = () => {
    if (!selected) return;
    navigator.clipboard.writeText(selected.content).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    });
  };

  const downloadZip = async () => {
    if (zipping) return;
    setZipping(true);
    try {
      const zip = new JSZip();
      for (const f of files) zip.file(f.path, f.content);
      // Scaffold manifest — purposes double as a build guide
      const manifest = [
        `# ${scaffold.project_type} — RepoScope scaffold`,
        "",
        "Generated by RepoScope from the repository graph (Row 1 entry files",
        "+ README + depth-1 tree). Boilerplate with TODOs — build it yourself,",
        "CodeCrafters style:",
        "",
        ...files.map((f) => `- \`${f.path}\` — ${f.purpose || "starter file"}`),
      ].join("\n");
      zip.file("SCAFFOLD.md", manifest);
      const blob = await zip.generateAsync({ type: "blob" });
      downloadBlob(blob, `reposcope-scaffold-${scaffold.project_type.replace(/\W+/g, "-").toLowerCase()}.zip`);
      toast.success("Scaffold ZIP downloaded");
    } catch (e: unknown) {
      toast.error(e instanceof Error ? e.message : "ZIP failed");
    } finally {
      setZipping(false);
    }
  };

  const openInStackBlitz = () => {
    // StackBlitz "run" API: form POST creates a project from in-memory files
    const form = document.createElement("form");
    form.method = "POST";
    form.target = "_blank";
    form.action = "https://stackblitz.com/run";
    const add = (name: string, value: string) => {
      const input = document.createElement("input");
      input.type = "hidden";
      input.name = name;
      input.value = value;
      form.appendChild(input);
    };
    add("project[title]", `RepoScope scaffold — ${scaffold.project_type}`);
    add("project[description]", "Starter scaffold generated by RepoScope");
    add("project[template]", stackblitzTemplate(scaffold.project_type));
    for (const f of files) add(`project[files][${f.path}]`, f.content);
    document.body.appendChild(form);
    form.submit();
    document.body.removeChild(form);
    toast.success("Opening in StackBlitz…");
  };

  return (
    <div
      className="fixed inset-0 z-[80] flex items-center justify-center p-4 bg-black/40"
      role="dialog"
      aria-modal="true"
      aria-label="Starter scaffold"
      onClick={onClose}
    >
      <div
        className="card w-full max-w-5xl h-[85vh] flex flex-col p-5 !shadow-lg pop-in"
        onClick={(e) => e.stopPropagation()}
      >
        {/* Header */}
        <div className="flex items-center justify-between mb-3 shrink-0 gap-2 flex-wrap">
          <div className="min-w-0">
            <h2 className="h3 flex items-center gap-2">
              <Zap size={16} className="text-accent-amber" />
              Scaffold
              <span className="text-xs font-semibold text-accent-cyan bg-accent-cyan/10 border border-accent-cyan/25 rounded px-2 py-0.5">
                {scaffold.project_type}
              </span>
            </h2>
            <p className="text-xs text-text-muted mt-0.5">
              CodeCrafters-style starter — boilerplate + TODOs, rebuild it yourself
            </p>
          </div>
          <div className="flex items-center gap-2 shrink-0 flex-wrap">
            <button onClick={() => void downloadZip()} disabled={zipping} className="btn-primary !py-1.5 !px-3 !text-xs">
              <Download size={12} />
              {zipping ? "Zipping…" : "Download ZIP"}
            </button>
            <button onClick={openInStackBlitz} className="btn-secondary !py-1.5 !px-3 !text-xs">
              <ExternalLink size={12} />
              Open in StackBlitz
            </button>
            <button
              onClick={onClose}
              aria-label="Close"
              className="btn-ghost w-8 h-8 !p-0 items-center justify-center shrink-0"
            >
              <X size={15} />
            </button>
          </div>
        </div>

        {/* Body: tree | preview */}
        <div className="flex-1 min-h-0 flex flex-col md:flex-row gap-4">
          <div className="w-full md:w-64 shrink-0 max-h-48 md:max-h-none overflow-y-auto card-flat p-3">
            <FileTree
              rawNodes={rawNodes}
              embedded
              title="Scaffold files"
              selectedPath={selected?.path ?? null}
              onSelectFile={setSelectedPath}
              hideDownload
            />
          </div>
          <div className="flex-1 min-w-0 flex flex-col gap-2">
            {selected && (
              <>
                <div className="flex items-center justify-between gap-2">
                  <div className="min-w-0">
                    <div className="font-mono text-xs text-text-primary truncate">{selected.path}</div>
                    {selected.purpose && (
                      <div className="text-[11px] text-text-muted truncate">{selected.purpose}</div>
                    )}
                  </div>
                  <button onClick={copyContent} className="btn-ghost !py-1 !px-2 !text-2xs shrink-0">
                    {copied ? <Check size={11} className="text-accent-emerald" /> : <Copy size={11} />}
                    {copied ? "Copied" : "Copy"}
                  </button>
                </div>
                <pre
                  className="flex-1 min-h-0 overflow-auto rounded-lg bg-[#1E1B16] text-[#F5F1E8]
                    font-mono text-[12px] leading-relaxed p-3 m-0 whitespace-pre"
                  aria-label={`Code preview of ${selected.path}`}
                >
                  {selected.content}
                </pre>
              </>
            )}
          </div>
        </div>

        <p className="text-[11px] text-text-muted mt-3 shrink-0">
          Stage-based starter derived from the repo graph — never the full codebase.
        </p>
      </div>
    </div>
  );
}
